### ISSUE TITLE
Math Magicians: refactor with hooks❗️

### ISSUE THREAD

**Issue by flemton** [flemton/math-magicians#5]
Dear reviewer, I am creating this issue to in relation to the exercise ['refactor with hooks'](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_refactor_with_hooks.md)
In this exercise, micronauts were asked to refactor their class components for the 'Math magicians: components' but following the [requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md#project-requirements) of the project we were told to [use functional components](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_components.md#:~:text=Use%20functional%20components), so because of this, all my components were functional components, details below:
- Button component https://github.com/flemton/math-magicians/blob/9cd79819ecd6f18f48d787f89e25c82269ebc129/src/components/Calculator.js#L6-L12
- Calculator render component https://github.com/flemton/math-magicians/blob/9cd79819ecd6f18f48d787f89e25c82269ebc129/src/components/Calculator.js#L22-L55

__I hope this passes the requirements and ultimately gets my project approved, cheers 🥂__

**Comment by Alfredbis29** [comment]
# STATUS: APPROVED  
 ## Hi @flemton  ,
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Well structured files :white_check_mark:
 * No Linter errors :white_check_mark:
 * Good Job :+1: 
 
 Now you can merge it and move on :1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [ ] N/A keep doing great job :clap: 

 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by flemton** [comment]
Thank you very much sir for the thorough review
